-- OPENAI_BLIND_V1 prospective paper-research ledger.
-- One immutable structured model forecast per 15-minute window at T-7:30.
-- The input packet structurally excludes Kalshi prices/fair, Council votes,
-- Chair state and entry economics. The model has no live authority.
create table if not exists desk_openai_blind (
  ticker text not null,
  close_time timestamptz not null,
  taken_at timestamptz not null,
  secs_left double precision not null,
  study text not null,
  version integer not null,
  prompt_version text not null,
  model text not null,
  response_id text not null default '',
  input_hash text not null,
  input_packet jsonb not null,
  market_p double precision,
  fair_p double precision,
  p_up double precision not null,
  side text not null,
  conviction integer not null,
  regime text not null,
  strongest_evidence jsonb not null,
  contradictions jsonb not null,
  data_quality text not null,
  would_abstain boolean not null,
  chair_lean text not null,
  yes_ask double precision,
  no_ask double precision,
  entry_cents double precision,
  input_tokens integer,
  output_tokens integer,
  total_tokens integer,
  latency_ms integer not null,
  build_sha text not null default '',
  created_at timestamptz not null default now(),
  primary key (ticker, close_time),
  check (study = 'OPENAI_BLIND_V1'),
  check (side in ('UP', 'DOWN')),
  check (chair_lean in ('UP', 'DOWN', 'WAIT')),
  check (data_quality in ('GOOD', 'DEGRADED', 'POOR')),
  check (p_up >= 0 and p_up <= 1),
  check (market_p is null or (market_p >= 0 and market_p <= 1)),
  check (fair_p is null or (fair_p >= 0 and fair_p <= 1)),
  check (conviction >= 0 and conviction <= 100),
  check (secs_left <= 450 and secs_left > 438),
  check (entry_cents is null or (entry_cents > 0 and entry_cents < 100)),
  check (jsonb_typeof(input_packet) = 'object'),
  check (not (input_packet ? 'market')),
  check (not (input_packet ? 'council')),
  check (not (input_packet ? 'chair')),
  check (jsonb_typeof(strongest_evidence) = 'array'),
  check (jsonb_typeof(contradictions) = 'array')
);
create index if not exists desk_openai_blind_taken_idx on desk_openai_blind (taken_at desc);
create index if not exists desk_openai_blind_close_idx on desk_openai_blind (close_time desc);
