import test from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from 'vite';
import {readFileSync} from 'node:fs';
import {PGlite} from '@electric-sql/pglite';
import ts from 'typescript';
import vm from 'node:vm';
let vite,m;
async function setup(){if(m)return m;vite=await createServer({configFile:false,envDir:false,resolve:{alias:{'@':`${process.cwd()}/src`}},server:{middlewareMode:true,hmr:false},appType:'custom',logLevel:'silent'});const names=['skills','demo','bots','council-voice-shadow','signal-book-shadow','council-authority'];const modules=await Promise.all(names.map(n=>vite.ssrLoadModule(`/src/lib/desk/${n}.ts`)));m=Object.fromEntries(names.map((n,i)=>[n,modules[i]]));return m;}
test.after(async()=>await vite?.close());
test('pre-registered kills never promote a candidate',async()=>{const m=await setup(),kill=m['council-voice-shadow'].voiceKillDecision;const base={validWindows:20,invalidWindows:0,pairedDelta:0,integrityViolations:0};assert.equal(kill(base),'CONTINUE_SHADOW');assert.equal(kill({...base,pairedDelta:-100}),'KILL_ECONOMICS');assert.equal(kill({...base,invalidWindows:2}),'PAUSE_CAPTURE');assert.equal(kill({...base,integrityViolations:1}),'KILL_INTEGRITY');assert.equal(kill({...base,pairedDelta:NaN}),'PAUSE_INVALID_SUMMARY');assert.equal(kill({...base,pairedDelta:1000}),'CONTINUE_SHADOW');});
async function fixture(){const m=await setup(),learner=m.skills.freshLearner();const snap=m.demo.demoTick(m.demo.newDemoWindow(learner.window_memory,450_000),learner.window_memory);Object.assign(snap,{demo:false,as_of:1790937000000,close_time:1790937450000});const votes=m.bots.runBots(snap,learner);const drift=votes.find(v=>v.seat==='DRIFT');Object.assign(drift,{lean:'WAIT',forced_sit:true,raw_lean:'UP',raw_conf:40,confidence:70,skill_used:'DRIFT.aligned_3h',skill_status:'LIVE',health:'LIVE',feed_age_s:1});return{snap,votes,learner,settings:{adaptive_bar:true,bar_override:null,mutes:[],beast:false},lastLean:'WAIT',now:snap.as_of};}
test('only the selected confidence gag is removed on cloned votes',async()=>{const f=await fixture(),m=await setup(),before=JSON.stringify(f);const a=m['council-voice-shadow'].withoutConfidenceGag(f.votes,f.snap,f.learner);const d=a.find(r=>r.vote.seat==='DRIFT');assert.equal(d.restored,true);assert.equal(d.vote.lean,'UP');assert.equal(d.vote.confidence,40);assert.equal(d.vote.forced_sit,false);assert.equal(JSON.stringify(f),before);});
test('bench, retired, context, stale, missing raw, and selected SIT remain closed',async()=>{const f=await fixture(),m=await setup(),v=f.votes.find(v=>v.seat==='DRIFT');for(const change of [{health:'DOWN'},{health:'STALE'},{raw_conf:NaN},{raw_conf:0},{raw_conf:55},{raw_lean:'WAIT'},{skill_used:'SIT'},{skill_status:'SHADOW'},{seat:'VEL',skill_status:'BENCH'},{seat:'WARDEN'},{seat:'ODDS'}])assert.equal(m['council-voice-shadow'].withoutConfidenceGag([{...v,...change}],f.snap,f.learner)[0].restored,false);f.learner.knobs.DRIFT={speak_offset:-4,benched_until:f.now+1};assert.equal(m['council-voice-shadow'].withoutConfidenceGag([v],f.snap,f.learner)[0].restored,false);});
test('actual Chair still applies authority after ungagging; immature and owner-held cards do not count',async()=>{const f=await fixture(),m=await setup(),card=f.learner.skills['DRIFT.aligned_3h'];Object.assign(card,{status:'LIVE',n:10,ev_n:10,wilson:.9,ev:5});const a=m['council-voice-shadow'].evaluateCouncilVoice(f);assert.ok(a.restored.includes('DRIFT'));assert.equal(a.booked,false);assert.equal(a.candidate.rows.find(r=>r.seat==='DRIFT').contribution,0);Object.assign(card,{n:100,ev_n:100,manual_hold:true});const b=m['council-voice-shadow'].evaluateCouncilVoice(f);assert.equal(b.candidate.rows.find(r=>r.seat==='DRIFT').contribution,0);});
test('mature ungagged vote passes the unchanged authority door, while input learner and control remain unchanged',async()=>{const f=await fixture(),m=await setup();Object.assign(f.learner.skills['DRIFT.aligned_3h'],{status:'LIVE',n:100,ev_n:100,wilson:.9,ev:5,manual_hold:false,min_regime_n:undefined,min_walkforward_n:undefined});f.votes=f.votes.filter(v=>v.seat==='DRIFT');f.learner.seat_n.DRIFT=100;f.learner.seat_hits.DRIFT=80;const before=JSON.stringify(f);const v=m['council-voice-shadow'].withoutConfidenceGag(f.votes,f.snap,f.learner).find(r=>r.vote.seat==='DRIFT').vote;assert.equal(m['council-authority'].directionalHoldReason(v,f.learner,f.snap.regime_key),null);const pair=m['council-voice-shadow'].evaluateCouncilVoice(f);assert.equal(pair.control.rows.find(r=>r.seat==='DRIFT').contribution,0);assert.ok(pair.candidate.rows.find(r=>r.seat==='DRIFT').contribution>0);assert.equal(JSON.stringify(f),before);});
test('future, stale, demo and expired frames fail closed',async()=>{const f=await fixture(),m=await setup();for(const change of [{now:f.now-1},{now:f.now+9000},{now:f.snap.close_time},{snap:{...f.snap,demo:true}}])assert.throws(()=>m['council-voice-shadow'].evaluateCouncilVoice({...f,...change}));});
test('generic signal book grades components for every bot, once per exact window, using own direction and fee',async()=>{const m=await setup(),s=m['signal-book-shadow'],close=900_000;const seats=['WICK','TAPE','PULSE','VEL','VOLT','WHALE','CARRY','CASCADE','EXHAUST','STREAK','DRIFT','STRIKE','CHAIN','INDEX','CLOCK','ODDS','CHEAP','FADE','WARDEN','WIRE','ORBIT'];const receipts=seats.map(seat=>({signal:{seat,kind:'synthetic-component',version:'v1',side:'UP',confidence:60,at:10},ask:82,fee:2}));const blank=s.blankSignalBook(),window={ticker:'test',close,winner:'UP',source:'kalshi-result',gradedAt:close};const a=s.gradeSignals(blank,window,[...receipts,...receipts]);assert.equal(Object.keys(a.stats).length,21);for(const st of Object.values(a.stats)){assert.equal(st.n,1);assert.equal(st.hits,1);assert.equal(st.ev,16);}assert.equal(Object.keys(blank.stats).length,0);assert.deepEqual(s.gradeSignals(a,window,receipts),a);assert.equal(Object.keys(s.gradeSignals(blank,{...window,source:'spot-derived'},receipts).stats).length,0);assert.equal(Object.keys(s.gradeSignals(blank,{...window,gradedAt:close-1},receipts).stats).length,0);assert.throws(()=>s.tuneSignals(a,receipts.map(r=>r.signal),close));});
test('bad components fold individually; good components scale independently; future signals never tune',async()=>{const m=await setup(),s=m['signal-book-shadow'];let book=s.blankSignalBook();for(let n=1;n<=20;n++){const close=n*900_000;book=s.gradeSignals(book,{ticker:'t'+n,close,winner:'UP',source:'kalshi-result',gradedAt:close},['good','bad'].map(kind=>({signal:{seat:'DRIFT',kind,version:'v1',side:kind==='good'?'UP':'DOWN',confidence:60,at:close-1000},ask:82,fee:2})));}const at=20*900_000+1000,out=s.tuneSignals(book,['good','bad'].map(kind=>({seat:'DRIFT',kind,version:'v1',side:kind==='good'?'UP':'DOWN',confidence:60,at})),at);assert.ok(out[0].shadow_confidence>60);assert.equal(out[1].shadow_confidence,0);assert.throws(()=>s.tuneSignals(book,[{...out[0],at:at+1}],at));});
test('public records use actual SQL: official-only, raw vs final cohorts, missing seats and no writes',async()=>{const db=new PGlite();try{await db.exec('create table desk_ledger_research(close_time timestamptz,seats jsonb,source text,winner text)');const at=Date.parse('2026-10-02T12:00:00Z');for(const [source,winner,lean] of [['kalshi-result','UP','WAIT'],['kalshi-result','DOWN','DOWN'],['spot-derived','UP','UP']])await db.query('insert into desk_ledger_research values($1,$2,$3,$4)',[new Date(at-1000).toISOString(),JSON.stringify({DRIFT:{raw_lean:'UP',lean}}),source,winner]);const sql=async(strings,...values)=>{let q=strings[0];for(let i=0;i<values.length;i++)q+=`$${i+1}`+strings[i+1];return(await db.query(q,values)).rows;};const exp={};const code=ts.transpileModule(readFileSync('src/lib/desk/bot-records.server.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;vm.runInNewContext(code,{exports:exp,require:k=>k==='@/lib/db'?{getSql:async()=>sql}:k==='./types'?{SEAT_IDS:['DRIFT','WICK']}:k==='./crew'?{NON_VOTERS:[],RETIRED_SEATS:{}}:assert.fail(k),Date});const report=await exp.botRecords(at);assert.equal(report.rows[0].windows,2);assert.equal(report.rows[0].raw_hits,1);assert.equal(report.rows[0].final_hits,1);assert.equal(report.rows[0].suppressed,1);assert.equal(report.rows[1].raw_n,0);assert.equal((await db.query('select count(*)::int as n from desk_ledger_research')).rows[0].n,3);}finally{await db.close();}});

test('delayed official grades are unavailable before their actual receipt time',async()=>{const m=await setup(),s=m['signal-book-shadow'];const signal={seat:'DRIFT',kind:'delay',version:'v1',side:'UP',confidence:60,at:100};const book=s.gradeSignals(s.blankSignalBook(),{ticker:'t',close:900000,winner:'UP',source:'kalshi-result',gradedAt:910000},[{signal,ask:82,fee:2}]);assert.throws(()=>s.tuneSignals(book,[{...signal,at:905000}],905000));assert.equal(s.tuneSignals(book,[{...signal,at:911000}],911000).length,1);});
