import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createServer} from 'vite';
import {PGlite} from '@electric-sql/pglite';
import ts from 'typescript';
import vm from 'node:vm';
import crypto from 'node:crypto';
import zlib from 'node:zlib';
let vite,m;
async function setup(){if(m)return m;vite=await createServer({configFile:false,envDir:false,resolve:{alias:{'@':`${process.cwd()}/src`}},server:{middlewareMode:true,hmr:false},appType:'custom',logLevel:'silent'});const names=['skills','demo','bots','council-voice-book','council-voice-shadow','selective-entry','council-voice-replay'];const mods=await Promise.all(names.map(n=>vite.ssrLoadModule(`/src/lib/desk/${n}.ts`)));m=Object.fromEntries(names.map((n,i)=>[n,mods[i]]));return m;}
test.after(async()=>await vite?.close());
const close=Date.parse('2026-10-02T12:15:00Z'), open=close-900000;
async function fixture(){const m=await setup(),L=m.skills.freshLearner();for(const [seat,card] of [['DRIFT','DRIFT.aligned_3h'],['CHAIN','CHAIN.oi_with_price']]){L.seat_n[seat]=100;L.seat_hits[seat]=80;L.seat_w[seat]=.2;Object.assign(L.skills[card],{status:'LIVE',n:100,ev_n:100,wilson:.8,ev:5,manual_hold:false,min_walkforward_n:undefined,min_regime_n:undefined});}L.window_memory.entry_lean='DOWN';
const snap=m.demo.demoTick(m.demo.newDemoWindow(L.window_memory,900000),L.window_memory);Object.assign(snap,{demo:false,as_of:open,close_time:close,ticker:'KXBTC15M-26OCT020815-15',mins_left:15,secs_left:900,yes_ask:85,yes_bid:84,no_ask:16,no_bid:15,yes_bid_size:7,no_bid_size:5,edge_up:6,edge_down:-8,fair_yes:90,lab_fair_yes:92,lab_age_s:1,fee_yes:2,fee_no:2,spread_cents:1,leftover_cents:-1,spot:80000,strike:79000,spot_age_s:1,quote_age_s:1,print_age_s:1,quote_seq:1,obs:{receipt_ts:open-1000,gap:'ok'},health:{spot_ok:true,kalshi_ok:true,spot:'LIVE',kalshi:'LIVE',derivs:'LIVE',spot_divergent:false,basis_wide:false},atr_pct:.2,phase:'ENTRY',regime_key:'integration',session:'US_AM',chalk:false});
const votes=[['DRIFT','DRIFT.aligned_3h'],['CHAIN','CHAIN.oi_with_price']].map(([seat,skill_used])=>({seat,skill_used,lean:'WAIT',raw_lean:'UP',raw_conf:51,forced_sit:true,confidence:70,features:{},reasoning:'synthetic paired book',skill_status:'LIVE',shadow:null,paper:[],thresh_used:[],skill_n:100,skill_hits:80,skill_wilson:.8,hypothesis:'',evidence:[],counter:'',invalidate_if:'',health:'LIVE',feed_age_s:1,eyes:'',phase:'ENTRY'}));
return {snap,votes,learner:L,settings:{adaptive_bar:true,bar_override:.01,mutes:[],beast:false},now:open,ready:true};}
function at(f,t){return {...f,now:t,snap:{...f.snap,as_of:t,mins_left:(close-t)/60000,secs_left:(close-t)/1000,obs:{...f.snap.obs,receipt_ts:t-1000}}};}
test('real paired pipeline restores only candidate, qualifies current team/quote and isolates risk and inputs',async()=>{const m=await setup(),f=await fixture(),book=m['council-voice-book'];const before=JSON.stringify(f);let state=book.freshVoiceBooks(open),fill=null;for(let n=0;n<100;n++){const r=book.stepVoiceBooks(state,at(f,open+n*4000));state=r.state;fill??=r.candidate.fill;}assert.ok(fill,'candidate earns a rule-qualified simulated fill');assert.equal(state.control.calls.length,0);assert.equal(state.candidate.calls.length,1);assert.equal(fill.cents,85);assert.equal(JSON.stringify(f),before);const r=book.stepVoiceBooks(state,at(f,open+400000));assert.equal(r.candidate.fill,null,'one entry only');});
test('book boundary retains floor, current edge, resting size, owner hold and fresh clocks',async()=>{const m=await setup(),f=await fixture(),b=m['council-voice-book'];for(const changes of [{yes_ask:79},{edge_up:0},{no_bid_size:0}]){let state=b.freshVoiceBooks(open);for(let n=0;n<10;n++)state=b.stepVoiceBooks(state,at({...f,snap:{...f.snap,...changes}},open+n*4000)).state;assert.equal(state.candidate.calls.length,0);}for(const changed of [{ready:false},{now:open-1},{snap:{...f.snap,demo:true}},{now:close}])assert.throws(()=>b.stepVoiceBooks(b.freshVoiceBooks(open),{...f,...changed}));Object.assign(f.learner.skills['DRIFT.aligned_3h'],{manual_hold:true});let state=b.freshVoiceBooks(open);for(let n=0;n<10;n++)state=b.stepVoiceBooks(state,at(f,open+n*4000)).state;assert.equal(state.candidate.calls.length,0);});
test('duplicate frames cannot advance confirmation; official grade is exact, idempotent and fee-aware',async()=>{const m=await setup(),f=await fixture(),b=m['council-voice-book'];const first=b.stepVoiceBooks(b.freshVoiceBooks(open),f);assert.throws(()=>b.stepVoiceBooks(first.state,f));const state=b.freshVoiceBooks(open);state.candidate.calls=[{id:'c',t:open,ticker:f.snap.ticker,close_time:close,lean:'UP',cents:85,settle:null,flipped:false}];const g={ticker:f.snap.ticker,close,winner:'UP',source:'kalshi-result',at:close+5000};const r=b.gradeVoiceBooks(state,g);assert.equal(r.control,0);assert.equal(r.candidate,14);assert.equal(r.delta,14);assert.deepEqual(b.gradeVoiceBooks(r.state,g),r);assert.throws(()=>b.gradeVoiceBooks(state,{...g,source:'spot-derived'}));assert.throws(()=>b.gradeVoiceBooks(state,{...g,at:close-1}));assert.equal(state.candidate.calls[0].settle,null);});
async function harness(options={}){const m=await setup(),db=new PGlite();await db.exec(readFileSync('migrations/0075_desk_council_voice.sql','utf8'));await db.exec(readFileSync('migrations/0075_desk_council_voice.sql','utf8'));await db.exec('create table desk_ledger_research(ticker text,close_time timestamptz,winner text,source text)');const sql=async(strings,...values)=>{let q=strings[0];for(let i=0;i<values.length;i++)q+=`$${i+1}`+strings[i+1];return (await db.query(q,values)).rows;};sql.query=async(q,v)=>(await db.query(q,v)).rows;const exp={};const code=ts.transpileModule(readFileSync('src/lib/desk/council-voice-collector.server.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;vm.runInNewContext(code,{exports:exp,require:k=>k==='node:crypto'?crypto:k==='node:zlib'?zlib:k==='@/lib/db'?{getSql:async()=>sql,dbPoolStats:()=>null}:k==='./council-voice-book'?m['council-voice-book']:k==='./council-voice-replay'?m['council-voice-replay']:k==='./council-voice-shadow'?m['council-voice-shadow']:k==='./selective-entry.ts'?m['selective-entry']:k==='./resource-governor-witness.ts'?{readResourceGovernorWitness:()=>null}:k==='./resource-governor.ts'?{}:assert.fail(k),process:{env:options.env??{}},Buffer,Date:options.Date??Date,JSON,Object,Number,Math,Array,Error,globalThis:options.root??{},setInterval:()=>assert.fail('disabled timer')});return {db,sql,exp};}
test('durable manifest, atomic frame/replay commit, canonical official grade and restart identity',async()=>{const h=await harness(),f=await fixture();try{assert.equal(h.exp.ensureVoiceCapture(),'disabled');await h.exp.voiceCaptureTick();assert.equal((await h.db.query('select count(*)::int n from desk_voice_meta')).rows[0].n,0);const a=await h.exp.initializeVoiceCapture(h.sql,open-1,'abcdef0');const r=await h.exp.initializeVoiceCapture(h.sql,open+60000,'abcdef0');assert.equal(a.start_ms,r.start_ms);assert.equal(Number(a.end_ms)-Number(a.start_ms),21*86400000);assert.equal((await h.db.query('select count(*)::int n from desk_voice_windows')).rows[0].n,2016);
const before=JSON.stringify(f);await h.exp.captureVoiceFrame(h.sql,f);assert.equal(JSON.stringify(f),before);const replay=(await h.db.query('select f.input_gzip,w.replay_base from desk_voice_frames f join desk_voice_windows w using(experiment,close_ms)')).rows[0];const decoded=(await setup())['council-voice-replay'].restoreVoiceReplay(JSON.parse(zlib.gunzipSync(Buffer.from(replay.replay_base,'base64')).toString()),JSON.parse(zlib.gunzipSync(Buffer.from(replay.input_gzip,'base64')).toString()));assert.deepEqual(decoded.input,JSON.parse(JSON.stringify(f)));const replayed=(await setup())['council-voice-book'].stepVoiceBooks(decoded.state_before,decoded.input);assert.equal(replayed.state.last,f.snap.as_of);const version=(await h.db.query('select revision from desk_voice_meta')).rows[0].revision;await assert.rejects(h.exp.captureVoiceFrame(h.sql,f));assert.equal((await h.db.query('select revision from desk_voice_meta')).rows[0].revision,version);
await h.db.query('update desk_voice_windows set last_ms=$1 where close_ms=$2',[close-4000,close]);await h.db.query('insert into desk_ledger_research values($1,$2,$3,$4)',[f.snap.ticker,new Date(close).toISOString(),'UP','spot-derived']);await h.exp.gradeVoiceCapture(h.sql,close+1000);assert.equal((await h.db.query('select result from desk_voice_windows where close_ms=$1',[close])).rows[0].result,null);await h.db.query("update desk_ledger_research set source='kalshi-result'");await h.exp.gradeVoiceCapture(h.sql,close+2000);const outcome=(await h.db.query('select result from desk_voice_windows where close_ms=$1',[close])).rows[0].result;assert.equal(outcome.valid,true);assert.equal(outcome.delta,0);await h.exp.gradeVoiceCapture(h.sql,close+4000);assert.deepEqual((await h.db.query('select result from desk_voice_windows where close_ms=$1',[close])).rows[0].result,outcome);
}finally{await h.db.close();}});
test('durable skips cannot become zero-return valid windows; changed build kills integrity',async()=>{const h=await harness(),f=await fixture();try{await h.exp.initializeVoiceCapture(h.sql,open-1,'abcdef0');await h.exp.excludeVoiceWindow(h.sql,close,'governor skip');await h.exp.captureVoiceFrame(h.sql,f);await h.db.query('update desk_voice_windows set last_ms=$1 where close_ms=$2',[close-4000,close]);await h.db.query('insert into desk_ledger_research values($1,$2,$3,$4)',[f.snap.ticker,new Date(close).toISOString(),'UP','kalshi-result']);await h.exp.gradeVoiceCapture(h.sql,close+1000);const outcome=(await h.db.query('select result from desk_voice_windows where close_ms=$1',[close])).rows[0].result;assert.equal(outcome.valid,false);assert.equal(outcome.delta,null);await assert.rejects(h.exp.initializeVoiceCapture(h.sql,close+1000,'abcdef1'));assert.equal((await h.db.query('select status from desk_voice_meta')).rows[0].status,'KILL_INTEGRITY');}finally{await h.db.close();}});

test('gaps invalidate later same-day risk; absence never resets risk to zero',async()=>{const m=await setup(),f=await fixture(),b=m['council-voice-book'];let state=b.stepVoiceBooks(b.freshVoiceBooks(open),f).state;const gap=b.stepVoiceBooks(state,at(f,open+20000));assert.match(gap.invalid,/gap/);assert.ok(gap.state.unknownDays.length);state=gap.state;for(let t=24000;t<400000;t+=4000){const r=b.stepVoiceBooks(state,at(f,open+t));assert.match(r.invalid,/risk history/);assert.equal(r.candidate.fill,null);state=r.state;}});
test('fully absent capture is counted invalid; future receipt kills and conflicts cannot partially advance state',async()=>{const h=await harness(),f=await fixture();try{await h.exp.initializeVoiceCapture(h.sql,open-1,'abcdef0');await h.exp.gradeVoiceCapture(h.sql,close+1000);assert.equal((await h.db.query('select invalid from desk_voice_windows where close_ms=$1',[close])).rows[0].invalid,'incomplete full-window capture');const revision=(await h.db.query('select revision from desk_voice_meta')).rows[0].revision;await h.db.query('update desk_voice_windows set ticker=$1 where close_ms=$2',['different-ticker',close]);await assert.rejects(h.exp.captureVoiceFrame(h.sql,f));assert.equal((await h.db.query('select revision from desk_voice_meta')).rows[0].revision,revision);await assert.rejects(h.exp.captureVoiceFrame(h.sql,{...f,now:open-1}));assert.equal((await h.db.query('select status from desk_voice_meta')).rows[0].status,'KILL_INTEGRITY');}finally{await h.db.close();}});

test('replay footprint and evaluation timing benchmark on a full SYNTHETIC window',async()=>{const m=await setup(),f=await fixture(),b=m['council-voice-book'];let state=b.freshVoiceBooks(open);const base=JSON.parse(JSON.stringify({input:f,state_before:state}));let total=zlib.gzipSync(JSON.stringify(base)).toString('base64').length,max=0;const started=performance.now();for(let n=0;n<225;n++){const input=at(f,open+n*4000);const bytes=zlib.gzipSync(JSON.stringify(m['council-voice-replay'].voiceReplayDelta(base,{input,state_before:state})));const restored=m['council-voice-replay'].restoreVoiceReplay(base,JSON.parse(zlib.gunzipSync(bytes).toString()));assert.deepEqual(restored,JSON.parse(JSON.stringify({input,state_before:state})));const r=b.stepVoiceBooks(state,input);const output=JSON.stringify({gzip:zlib.gzipSync(JSON.stringify({control:r.control,candidate:r.candidate,restored:r.restored})).toString('base64')});const stored=bytes.toString('base64').length+output.length;total+=stored;max=Math.max(max,bytes.length);state=r.state;}console.log(JSON.stringify({synthetic_only:true,frames:225,encoded_replay_bytes:total,max_compressed_input_bytes:max,evaluation_and_compression_ms:Math.round(performance.now()-started)}));assert.ok(max<=65536);assert.ok(total<=2097152,'full window fits the frozen replay budget');});
test('owner report route is header-only and never starts or changes the study',()=>{const s=readFileSync('server/routes/research/council-voice.get.ts','utf8');assert.match(s,/x-desk-admin/);assert.match(s,/status:404/);assert.match(s,/no-store/);assert.ok(!s.includes('ensureVoiceCapture'));assert.ok(!s.includes('searchParams'));const collector=readFileSync('src/lib/desk/council-voice-collector.server.ts','utf8');for(const text of ['update desk_state','insert into desk_ledger','sendPush','notifyCall','placeOrder'])assert.ok(!collector.includes(text));});

test('complete durable paired book grades a real simulated entry after fees and retracts uncertain later risk',async()=>{const h=await harness(),f=await fixture();try{await h.exp.initializeVoiceCapture(h.sql,open-1,'abcdef0');for(let n=0;n<225;n++)await h.exp.captureVoiceFrame(h.sql,at(f,open+n*4000));await h.db.query('insert into desk_ledger_research values($1,$2,$3,$4)',[f.snap.ticker,new Date(close).toISOString(),'UP','kalshi-result']);await h.exp.gradeVoiceCapture(h.sql,close+1000);const result=(await h.db.query('select result,changed from desk_voice_windows where close_ms=$1',[close])).rows[0];assert.equal(result.result.valid,true);assert.equal(result.changed,true);assert.equal(result.result.control,0);assert.equal(result.result.candidate,14);assert.equal(result.result.delta,14);const state=(await h.db.query('select state from desk_voice_meta')).rows[0].state;assert.equal(state.candidate.calls[0].settle,100);assert.equal((await h.db.query('select count(*)::int n from desk_voice_frames')).rows[0].n,225);await h.db.query("update desk_voice_windows set result='{"+'"valid":true,"delta":14'+"}'::jsonb where close_ms=$1",[close+900000]);await h.exp.excludeVoiceWindow(h.sql,close,'lost closing observation');const later=(await h.db.query('select invalid,result from desk_voice_windows where close_ms=$1',[close+900000])).rows[0];assert.match(later.invalid,/risk history/);assert.equal(later.result,null);}finally{await h.db.close();}});

test('expired commit and busy sampling durably invalidate prospective coverage',async()=>{const root={__voiceCapture:{busy:true,boot:open-1,initialized:true,lastGrade:open+4000,error:null,timer:null}},h=await harness({root,env:{COUNCIL_VOICE_V1_ENABLED:'true'},Date:{now:()=>open+4000}}),f=await fixture();try{await h.exp.initializeVoiceCapture(h.sql,open-1,'abcdef0');await h.exp.voiceCaptureTick();assert.deepEqual(Array.from(root.__voiceCapture.busySkips),[close]);root.__voiceCapture.busy=false;await h.exp.voiceCaptureTick();assert.equal(root.__voiceCapture.busySkips.length,0);assert.ok((await h.db.query('select invalid from desk_voice_windows where close_ms=$1',[close])).rows[0].invalid);assert.equal(root.__voiceCapture.busy,false);assert.equal(await h.exp.captureVoiceFrame(h.sql,f,()=>close),null);assert.equal((await h.db.query('select count(*)::int n from desk_voice_frames')).rows[0].n,0);}finally{await h.db.close();}});
