/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ArenaRouteImport } from './routes/arena'
import { Route as ChamberRouteImport } from './routes/chamber'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as SeatIdRouteImport } from './routes/seat.$id'
import { Route as WindowTickerRouteImport } from './routes/window.$ticker'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ArenaRoute = ArenaRouteImport.update({
  id: '/arena',
  path: '/arena',
  getParentRoute: () => rootRouteImport,
} as any)
const ChamberRoute = ChamberRouteImport.update({
  id: '/chamber',
  path: '/chamber',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const SeatIdRoute = SeatIdRouteImport.update({
  id: '/seat/$id',
  path: '/seat/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WindowTickerRoute = WindowTickerRouteImport.update({
  id: '/window/$ticker',
  path: '/window/$ticker',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/arena': typeof ArenaRoute
  '/chamber': typeof ChamberRoute
  '/faq': typeof FaqRoute
  '/legal': typeof LegalRoute
  '/seat/$id': typeof SeatIdRoute
  '/window/$ticker': typeof WindowTickerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/arena': typeof ArenaRoute
  '/chamber': typeof ChamberRoute
  '/faq': typeof FaqRoute
  '/legal': typeof LegalRoute
  '/seat/$id': typeof SeatIdRoute
  '/window/$ticker': typeof WindowTickerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/arena': typeof ArenaRoute
  '/chamber': typeof ChamberRoute
  '/faq': typeof FaqRoute
  '/legal': typeof LegalRoute
  '/seat/$id': typeof SeatIdRoute
  '/window/$ticker': typeof WindowTickerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/arena'
    | '/chamber'
    | '/faq'
    | '/legal'
    | '/seat/$id'
    | '/window/$ticker'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/arena'
    | '/chamber'
    | '/faq'
    | '/legal'
    | '/seat/$id'
    | '/window/$ticker'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/arena'
    | '/chamber'
    | '/faq'
    | '/legal'
    | '/seat/$id'
    | '/window/$ticker'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ArenaRoute: typeof ArenaRoute
  ChamberRoute: typeof ChamberRoute
  FaqRoute: typeof FaqRoute
  LegalRoute: typeof LegalRoute
  SeatIdRoute: typeof SeatIdRoute
  WindowTickerRoute: typeof WindowTickerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arena': {
      id: '/arena'
      path: '/arena'
      fullPath: '/arena'
      preLoaderRoute: typeof ArenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chamber': {
      id: '/chamber'
      path: '/chamber'
      fullPath: '/chamber'
      preLoaderRoute: typeof ChamberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seat/$id': {
      id: '/seat/$id'
      path: '/seat/$id'
      fullPath: '/seat/$id'
      preLoaderRoute: typeof SeatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/window/$ticker': {
      id: '/window/$ticker'
      path: '/window/$ticker'
      fullPath: '/window/$ticker'
      preLoaderRoute: typeof WindowTickerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ArenaRoute: ArenaRoute,
  ChamberRoute: ChamberRoute,
  FaqRoute: FaqRoute,
  LegalRoute: LegalRoute,
  SeatIdRoute: SeatIdRoute,
  WindowTickerRoute: WindowTickerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
