/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ArenaRouteImport } from './routes/arena'
import { Route as BoardRouteImport } from './routes/board'
import { Route as BooksRouteImport } from './routes/books'
import { Route as ChamberRouteImport } from './routes/chamber'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FloorRouteImport } from './routes/floor'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as HourRouteImport } from './routes/hour'
import { Route as LabRouteImport } from './routes/lab'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as RecordRouteImport } from './routes/record'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as SeatIdRouteImport } from './routes/seat.$id'
import { Route as TrainingIndexRouteImport } from './routes/training.index'
import { Route as TrainingCoachRouteImport } from './routes/training.$coach'
import { Route as WindowTickerRouteImport } from './routes/window.$ticker'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ArenaRoute = ArenaRouteImport.update({
  id: '/arena',
  path: '/arena',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardRoute = BoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const ChamberRoute = ChamberRouteImport.update({
  id: '/chamber',
  path: '/chamber',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FloorRoute = FloorRouteImport.update({
  id: '/floor',
  path: '/floor',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const HourRoute = HourRouteImport.update({
  id: '/hour',
  path: '/hour',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordRoute = RecordRouteImport.update({
  id: '/record',
  path: '/record',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const SeatIdRoute = SeatIdRouteImport.update({
  id: '/seat/$id',
  path: '/seat/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingIndexRoute = TrainingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TrainingRoute,
} as any)
const TrainingCoachRoute = TrainingCoachRouteImport.update({
  id: '/$coach',
  path: '/$coach',
  getParentRoute: () => TrainingRoute,
} as any)
const WindowTickerRoute = WindowTickerRouteImport.update({
  id: '/window/$ticker',
  path: '/window/$ticker',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/arena': typeof ArenaRoute
  '/board': typeof BoardRoute
  '/books': typeof BooksRoute
  '/chamber': typeof ChamberRoute
  '/desk': typeof DeskRoute
  '/faq': typeof FaqRoute
  '/floor': typeof FloorRoute
  '/gallery': typeof GalleryRoute
  '/hour': typeof HourRoute
  '/lab': typeof LabRoute
  '/legal': typeof LegalRoute
  '/record': typeof RecordRoute
  '/training': typeof TrainingRouteWithChildren
  '/seat/$id': typeof SeatIdRoute
  '/training/$coach': typeof TrainingCoachRoute
  '/window/$ticker': typeof WindowTickerRoute
  '/training/': typeof TrainingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/arena': typeof ArenaRoute
  '/board': typeof BoardRoute
  '/books': typeof BooksRoute
  '/chamber': typeof ChamberRoute
  '/desk': typeof DeskRoute
  '/faq': typeof FaqRoute
  '/floor': typeof FloorRoute
  '/gallery': typeof GalleryRoute
  '/hour': typeof HourRoute
  '/lab': typeof LabRoute
  '/legal': typeof LegalRoute
  '/record': typeof RecordRoute
  '/seat/$id': typeof SeatIdRoute
  '/training/$coach': typeof TrainingCoachRoute
  '/window/$ticker': typeof WindowTickerRoute
  '/training': typeof TrainingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/arena': typeof ArenaRoute
  '/board': typeof BoardRoute
  '/books': typeof BooksRoute
  '/chamber': typeof ChamberRoute
  '/desk': typeof DeskRoute
  '/faq': typeof FaqRoute
  '/floor': typeof FloorRoute
  '/gallery': typeof GalleryRoute
  '/hour': typeof HourRoute
  '/lab': typeof LabRoute
  '/legal': typeof LegalRoute
  '/record': typeof RecordRoute
  '/training': typeof TrainingRouteWithChildren
  '/seat/$id': typeof SeatIdRoute
  '/training/$coach': typeof TrainingCoachRoute
  '/window/$ticker': typeof WindowTickerRoute
  '/training/': typeof TrainingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/arena'
    | '/board'
    | '/books'
    | '/chamber'
    | '/desk'
    | '/faq'
    | '/floor'
    | '/gallery'
    | '/hour'
    | '/lab'
    | '/legal'
    | '/record'
    | '/training'
    | '/seat/$id'
    | '/training/$coach'
    | '/window/$ticker'
    | '/training/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/arena'
    | '/board'
    | '/books'
    | '/chamber'
    | '/desk'
    | '/faq'
    | '/floor'
    | '/gallery'
    | '/hour'
    | '/lab'
    | '/legal'
    | '/record'
    | '/seat/$id'
    | '/training/$coach'
    | '/window/$ticker'
    | '/training'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/arena'
    | '/board'
    | '/books'
    | '/chamber'
    | '/desk'
    | '/faq'
    | '/floor'
    | '/gallery'
    | '/hour'
    | '/lab'
    | '/legal'
    | '/record'
    | '/training'
    | '/seat/$id'
    | '/training/$coach'
    | '/window/$ticker'
    | '/training/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ArenaRoute: typeof ArenaRoute
  BoardRoute: typeof BoardRoute
  BooksRoute: typeof BooksRoute
  ChamberRoute: typeof ChamberRoute
  DeskRoute: typeof DeskRoute
  FaqRoute: typeof FaqRoute
  FloorRoute: typeof FloorRoute
  GalleryRoute: typeof GalleryRoute
  HourRoute: typeof HourRoute
  LabRoute: typeof LabRoute
  LegalRoute: typeof LegalRoute
  RecordRoute: typeof RecordRoute
  TrainingRoute: typeof TrainingRouteWithChildren
  SeatIdRoute: typeof SeatIdRoute
  WindowTickerRoute: typeof WindowTickerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arena': {
      id: '/arena'
      path: '/arena'
      fullPath: '/arena'
      preLoaderRoute: typeof ArenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chamber': {
      id: '/chamber'
      path: '/chamber'
      fullPath: '/chamber'
      preLoaderRoute: typeof ChamberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/floor': {
      id: '/floor'
      path: '/floor'
      fullPath: '/floor'
      preLoaderRoute: typeof FloorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hour': {
      id: '/hour'
      path: '/hour'
      fullPath: '/hour'
      preLoaderRoute: typeof HourRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/record': {
      id: '/record'
      path: '/record'
      fullPath: '/record'
      preLoaderRoute: typeof RecordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seat/$id': {
      id: '/seat/$id'
      path: '/seat/$id'
      fullPath: '/seat/$id'
      preLoaderRoute: typeof SeatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training/': {
      id: '/training/'
      path: '/'
      fullPath: '/training/'
      preLoaderRoute: typeof TrainingIndexRouteImport
      parentRoute: typeof TrainingRoute
    }
    '/training/$coach': {
      id: '/training/$coach'
      path: '/$coach'
      fullPath: '/training/$coach'
      preLoaderRoute: typeof TrainingCoachRouteImport
      parentRoute: typeof TrainingRoute
    }
    '/window/$ticker': {
      id: '/window/$ticker'
      path: '/window/$ticker'
      fullPath: '/window/$ticker'
      preLoaderRoute: typeof WindowTickerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TrainingRouteChildren {
  TrainingCoachRoute: typeof TrainingCoachRoute
  TrainingIndexRoute: typeof TrainingIndexRoute
}

const TrainingRouteChildren: TrainingRouteChildren = {
  TrainingCoachRoute: TrainingCoachRoute,
  TrainingIndexRoute: TrainingIndexRoute,
}

const TrainingRouteWithChildren = TrainingRoute._addFileChildren(
  TrainingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ArenaRoute: ArenaRoute,
  BoardRoute: BoardRoute,
  BooksRoute: BooksRoute,
  ChamberRoute: ChamberRoute,
  DeskRoute: DeskRoute,
  FaqRoute: FaqRoute,
  FloorRoute: FloorRoute,
  GalleryRoute: GalleryRoute,
  HourRoute: HourRoute,
  LabRoute: LabRoute,
  LegalRoute: LegalRoute,
  RecordRoute: RecordRoute,
  TrainingRoute: TrainingRouteWithChildren,
  SeatIdRoute: SeatIdRoute,
  WindowTickerRoute: WindowTickerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
