/**
 * Council Room V1 — SYNTHETIC test fixtures. Test-only; nothing in the app imports this.
 *
 * Real public rows could not be fetched from the build environment (egress to the
 * public site is denied), so every fixture is generated by the real Chamber
 * producers, validated by the real Phase 1A validator and mapped by the real
 * statementFromEvent. Tickers and times are invented but follow the verified
 * KXBTC15M identity format. Replace with sanitized public captures when supplied.
 */
import assert from "node:assert/strict";
import { statementFromEvent, type ChamberStatement } from "./chamber-reactions.ts";
import { maybeChairDirectionalEvent } from "./chamber-directional.ts";
import { maybeChairWaitEvent } from "./chamber-wait.ts";
import { maybeWardenHealthEvent } from "./chamber-health.ts";
import { labExperimentEvents } from "./chamber-lab.ts";
import { sweepCrewEvent } from "./chamber-sweep.ts";
import { validateSystemEvent, type PublicSystemEvent, type SystemEventInput } from "./system-events.ts";
import type { CallLogRow, ChairResult, Snapshot } from "./types.ts";

// SYNTHETIC window: KXBTC15M-26OCT021915-15 closes 19:15 America/New_York = 23:15 UTC.
export const TICKER = "KXBTC15M-26OCT021915-15";
export const CLOSE = Date.parse("2026-10-02T23:15:00Z");
export const T0 = CLOSE - 6 * 60_000;
export const RECEIVED = T0 + 30_000;

function asPublic(input: SystemEventInput | null): PublicSystemEvent {
  assert.ok(input, "producer returned null for a SYNTHETIC fixture");
  const ev = validateSystemEvent(input);
  return { ...ev, occurred_at: ev.occurred_at.toISOString() };
}

export function statementOf(input: SystemEventInput | null): ChamberStatement {
  const s = statementFromEvent(JSON.parse(JSON.stringify(asPublic(input))));
  assert.ok(s, "mapper refused a SYNTHETIC fixture");
  return s;
}

export function snap(over: Partial<Snapshot> = {}): Snapshot {
  return {
    as_of: T0,
    ticker: TICKER,
    close_time: CLOSE,
    yes_ask: 64,
    no_ask: 38,
    yes_bid: 62,
    no_bid: 36,
    fair_yes: 52,
    quote_age_s: 3,
    health: { kalshi: "LIVE" },
    obs: { last_ok_ts: T0 - 2_000, gap: "ok" },
    ...over,
  } as unknown as Snapshot;
}

function chair(over: Partial<ChairResult> = {}): ChairResult {
  return {
    lean: "WAIT",
    confidence: 40,
    score: 1,
    bar: 2,
    gates: [],
    hypothesis: "SYNTHETIC",
    evidence: [],
    counter: "",
    invalidate_if: "",
    wait_note: "score under the bar",
    quorum: { up: 2, down: 1, wait: 12 },
    ...over,
  } as unknown as ChairResult;
}

export const call: CallLogRow = { id: `${CLOSE}-UP-${T0}`, t: T0, ticker: TICKER, close_time: CLOSE, lean: "UP", cents: 81, settle: null, flipped: false };

export const SYNTHETIC = {
  book: () => statementOf(maybeChairDirectionalEvent(snap(), [call])),
  wait: () => statementOf(maybeChairWaitEvent(chair(), snap(), { kind: "wait" })),
  alert: () => statementOf(maybeWardenHealthEvent("LIVE", snap({ health: { kalshi: "STALE" }, quote_age_s: 90, obs: { last_ok_ts: T0 - 90_000, gap: "stale" } } as unknown as Partial<Snapshot>)).event),
  lab: () =>
    labExperimentEvents({
      candidate_id: "SYNTH_CANDIDATE_V1",
      label: "Synthetic specimen",
      control: false,
      frozen_at: "2026-09-30T00:00:00Z",
      why: "SYNTHETIC",
      n: 30,
      paired_n: 30,
      paired_delta: 1.2,
      observed_at: new Date(T0).toISOString(),
      control_id: "SYNTH_CONTROL",
    }).map(statementOf),
  sweep: () => statementOf(sweepCrewEvent({ t: new Date(T0).toISOString(), seat: "drift", action: "flag", detail: "SYNTHETIC detail", slug: "sweep-synth-drift-1", evidence: { reads: 40, spoke: 10, gagged: 2, mid_n: 8, grade_n: 30 } })),
};


/** A SYNTHETIC canonical paper call on an arbitrary quarter-hour window (UTC close). */
export function bookCallAt(closeMs: number, ticker: string, recordedMs = closeMs - 6 * 60_000): ChamberStatement {
  const row: CallLogRow = { id: `${closeMs}-DOWN-${recordedMs}`, t: recordedMs, ticker, close_time: closeMs, lean: "DOWN", cents: 82, settle: null, flipped: false };
  return statementOf(maybeChairDirectionalEvent(snap({ as_of: recordedMs, ticker, close_time: closeMs }), [row]));
}
