import { clamp, wilsonLower } from "./math";
import { SKILL_RULES } from "./dsl";
import { SEAT_BY_ID } from "./seats";
import { freshThresholds } from "./thresholds";
import type { Learner, LearnPhase, SeatId, SeatKnobs, SkillCard, SkillStatus } from "./types";
import { SEAT_IDS } from "./types";

export type SkillSeed = {
  id: string;
  owner: SeatId;
  question: string;
  eyes: string;
  fire_when: string;
  vote: string;
  conf_formula: string;
  invalidate_if: string;
  start: SkillStatus;
};

export const SKILL_SEEDS: SkillSeed[] = [
  {
    id: "WICK.pin_at_high",
    owner: "WICK",
    question: "Is this a wick reject at the high of the local range?",
    eyes: "1m candle location + upper wick / range",
    fire_when: "location HIGH AND upper_wick/range ≥ 0.55 AND bar closed",
    vote: "fade the push (DOWN)",
    conf_formula: "wick ratio as edge",
    invalidate_if: "opposite engulf or ret15 flips",
    start: "LIVE",
  },
  {
    id: "WICK.engulf_at_extreme",
    owner: "WICK",
    question: "Two-bar engulf at HIGH or LOW?",
    eyes: "last two 1m candles + location",
    fire_when: "engulf at HIGH or LOW",
    vote: "with the engulf",
    conf_formula: "body coverage as edge",
    invalidate_if: "opposite engulf",
    start: "SHADOW",
  },
  {
    id: "WICK.doji_after_run",
    owner: "WICK",
    question: "Doji after a 15m run?",
    eyes: "1m doji + |ret15|",
    fire_when: "doji AND |ret15| ≥ 0.25%",
    vote: "WAIT",
    conf_formula: "sit strength",
    invalidate_if: "next bar is a full body",
    start: "SHADOW",
  },
  {
    id: "WICK.hammer_at_low",
    owner: "WICK",
    question: "Hammer / dragonfly reject at the low of the local range?",
    eyes: "1m lower wick + location LOW",
    fire_when: "location LOW AND lower_wick/range ≥ 0.55 AND bar closed",
    vote: "fade the dump (UP)",
    conf_formula: "lower wick ratio as edge",
    invalidate_if: "next bar closes below the hammer low",
    start: "SHADOW",
  },
  {
    id: "WICK.amd",
    owner: "WICK",
    question: "ICT AMD: accumulation box, liquidity grab, then displacement?",
    eyes: "1m range box + sweep wick + close through the box",
    fire_when: "AMD phase DISTRIBUTION (manip printed, displacement started)",
    vote: "with displacement (against the sweep)",
    conf_formula: "amd quality × volume confirm",
    invalidate_if: "close back inside the accumulation box",
    start: "SHADOW",
  },
  {
    id: "WICK.liq_sweep",
    owner: "WICK",
    question: "Stop-hunt wick through a swing that closed back in?",
    eyes: "swing high/low vs last closed 1m wick",
    fire_when: "last bar sweeps a swing then closes back through it",
    vote: "against the sweep (mean-revert)",
    conf_formula: "wick ratio as edge",
    invalidate_if: "next close continues through the swing",
    start: "SHADOW",
  },
  {
    id: "WICK.morning_star",
    owner: "WICK",
    question: "Three-bar morning star at a low?",
    eyes: "last three 1m candles",
    fire_when: "bearish body + small star + bullish close above first midpoint",
    vote: "UP",
    conf_formula: "fixed 0.64, +vol confirm",
    invalidate_if: "next close back below the star low",
    start: "SHADOW",
  },
  {
    id: "WICK.evening_star",
    owner: "WICK",
    question: "Three-bar evening star at a high?",
    eyes: "last three 1m candles",
    fire_when: "bullish body + small star + bearish close below first midpoint",
    vote: "DOWN",
    conf_formula: "fixed 0.64, +vol confirm",
    invalidate_if: "next close back above the star high",
    start: "SHADOW",
  },
  {
    id: "WICK.tweezer",
    owner: "WICK",
    question: "Matching highs or lows at an extreme (tweezer)?",
    eyes: "last two 1m highs/lows",
    fire_when: "tweezer top at HIGH or tweezer bottom at LOW",
    vote: "fade the extreme",
    conf_formula: "fixed 0.58",
    invalidate_if: "close through the tweezer level",
    start: "SHADOW",
  },
  {
    id: "WICK.bos_close",
    owner: "WICK",
    question: "Close through last swing (break of structure)?",
    eyes: "swing highs/lows vs last close",
    fire_when: "close above last swing high or below last swing low",
    vote: "with the break",
    conf_formula: "fixed 0.6",
    invalidate_if: "next bar reclaims the broken swing",
    start: "SHADOW",
  },
  {
    id: "DRIFT.aligned_3h",
    owner: "DRIFT",
    question: "Are 5m/15m/30m returns aligned?",
    eyes: "ret5 ret15 ret30",
    fire_when: "same sign AND |ret15| ≥ 0.25%",
    vote: "that side",
    conf_formula: "|ret15| scaled",
    invalidate_if: "any horizon flips sign",
    start: "LIVE",
  },
  {
    id: "DRIFT.accel_impulse",
    owner: "DRIFT",
    question: "Is the last 5m carrying most of the 15m move (acceleration)?",
    eyes: "|ret5| vs |ret15| + volume",
    fire_when: "same sign AND |ret5| ≥ 42% of |ret15| AND |ret15| ≥ 0.25%",
    vote: "with the impulse",
    conf_formula: "ret5 share of ret15",
    invalidate_if: "ret5 flips against ret15",
    start: "SHADOW",
  },
  {
    id: "DRIFT.decaying_impulse",
    owner: "DRIFT",
    question: "Is the 15m move still printing while 5m has gone quiet?",
    eyes: "|ret5| << |ret15| same sign",
    fire_when: "same sign AND |ret5| < 16% of |ret15| AND |ret15| ≥ 0.25%",
    vote: "WAIT — impulse dying",
    conf_formula: "sit strength",
    invalidate_if: "ret5 re-accelerates with ret15",
    start: "SHADOW",
  },
  {
    id: "DRIFT.pullback_in_trend",
    owner: "DRIFT",
    question: "5m dip against a 15/30 stack that still has structure?",
    eyes: "ret5 vs ret15/30 + 1m structure",
    fire_when: "15=30, 5m opposite or flat, structure not against",
    vote: "with the 15m (buy/sell the dip)",
    conf_formula: "|ret15| scaled",
    invalidate_if: "5m makes a new extreme against 15m",
    start: "SHADOW",
  },
  {
    id: "DRIFT.mtf_stack",
    owner: "DRIFT",
    question: "Do 1m EMA, 5m EMA and 15m return all agree?",
    eyes: "EMA8/21 on 1m and 5m + ret15",
    fire_when: "EMA stack matches ret15 AND |ret15| ≥ 0.25%",
    vote: "with the stack",
    conf_formula: "|ret15| scaled",
    invalidate_if: "either EMA stack flips",
    start: "SHADOW",
  },
  {
    id: "DRIFT.chop_sit",
    owner: "DRIFT",
    question: "Are the three horizons mixed with no pullback?",
    eyes: "ret5/15/30 signs",
    fire_when: "not aligned AND not a pullback-in-trend",
    vote: "WAIT",
    conf_formula: "sit",
    invalidate_if: "horizons align or a clean pullback prints",
    start: "SHADOW",
  },
  {
    id: "STREAK.continue_young",
    owner: "STREAK",
    question: "Young official streak still agreeing with the YES book?",
    eyes: "last 8 Kalshi results + YES mid",
    fire_when: "streak_n ≤ 3 AND YES book agrees",
    vote: "continue",
    conf_formula: "streak length inverse",
    invalidate_if: "YES book breaks the streak side",
    start: "LIVE",
  },
  {
    id: "STREAK.fade_extended",
    owner: "STREAK",
    question: "Is the settled streak extended (≥5)?",
    eyes: "streak_n",
    fire_when: "streak_n ≥ 5",
    vote: "fade",
    conf_formula: "extension as edge",
    invalidate_if: "live path breaks",
    start: "SHADOW",
  },
  {
    id: "STREAK.mid_hold",
    owner: "STREAK",
    question: "Streak of 4 still agreeing with the YES book?",
    eyes: "streak_n = 4 + YES mid",
    fire_when: "streak_n = 4 AND YES book agrees",
    vote: "continue, smaller size",
    conf_formula: "fixed 0.5",
    invalidate_if: "YES book breaks or n hits 5",
    start: "SHADOW",
  },
  {
    id: "STREAK.live_break",
    owner: "STREAK",
    question: "Young official streak already broken by the YES book?",
    eyes: "Kalshi chips vs YES mid",
    fire_when: "streak_n 1–3 AND YES book opposite",
    vote: "WAIT",
    conf_formula: "sit",
    invalidate_if: "YES book reclaims the streak side",
    start: "SHADOW",
  },
  {
    id: "STREAK.alt_chop",
    owner: "STREAK",
    question: "Last four settled chips alternating?",
    eyes: "official Kalshi chips",
    fire_when: "last 4 directional chips flip every window",
    vote: "WAIT — no streak quality",
    conf_formula: "sit",
    invalidate_if: "two same-side chips print in a row",
    start: "SHADOW",
  },
  {
    id: "STREAK.yes_agrees",
    owner: "STREAK",
    question: "Does YES mid confirm a young/mid streak?",
    eyes: "YES¢ vs streak side",
    fire_when: "streak 1–4 AND YES ≥55 on UP or ≤45 on DOWN",
    vote: "continue",
    conf_formula: "fixed 0.56",
    invalidate_if: "YES crosses 50 against the streak",
    start: "SHADOW",
  },
  {
    id: "EXHAUST.1h_run_5m_flip",
    owner: "EXHAUST",
    question: "Fade a 1h run after a 5m flip at the extreme?",
    eyes: "1h candle + last six 5m",
    fire_when: "|1h ret| ≥ the run threshold (0.7%, tunable) AND price in top/bottom 20% AND 5m flipped",
    vote: "fade the 1h side",
    conf_formula: "run size * flip",
    invalidate_if: "5m resumes the 1h direction",
    start: "LIVE",
  },
  {
    id: "EXHAUST.climax_wick",
    owner: "EXHAUST",
    question: "Blow-off: 1h run at extreme + 5m wick against + volume?",
    eyes: "1h ret + 5m wick + vol",
    fire_when: "run at extreme, last 5m wick ≥45% against, vol confirms",
    vote: "fade the 1h",
    conf_formula: "wick ratio * run",
    invalidate_if: "next 5m marubozu resumes the run",
    start: "SHADOW",
  },
  {
    id: "EXHAUST.rsi_div",
    owner: "EXHAUST",
    question: "1h still running while 5m RSI has rolled over?",
    eyes: "1h ret vs 5m RSI",
    fire_when: "|1h| ≥ the run threshold (0.7%, tunable) AND RSI <42 on an up-run (or >58 on a down-run)",
    vote: "fade the 1h",
    conf_formula: "fixed 0.58",
    invalidate_if: "RSI reclaims 50 with the run",
    start: "SHADOW",
  },
  {
    id: "EXHAUST.failed_push",
    owner: "EXHAUST",
    question: "Second 5m push at the extreme failed to make a new high/low?",
    eyes: "last two 5m extremes vs 1h",
    fire_when: "run at extreme AND last 5m did not extend the prior 5m extreme",
    vote: "fade the 1h",
    conf_formula: "fixed 0.6",
    invalidate_if: "next 5m makes a new extreme with the run",
    start: "SHADOW",
  },
  {
    id: "EXHAUST.ema_cross_against",
    owner: "EXHAUST",
    question: "5m EMA8/21 stacked against a 1h run?",
    eyes: "5m EMA vs 1h ret",
    fire_when: "|1h| ≥ 1% AND 5m EMA stack opposite the 1h",
    vote: "fade the 1h",
    conf_formula: "fixed 0.57",
    invalidate_if: "5m EMA recrosses with the 1h",
    start: "SHADOW",
  },
  {
    id: "EXHAUST.inside_after_run",
    owner: "EXHAUST",
    question: "5m inside bar after a 1h run?",
    eyes: "last two 5m ranges",
    fire_when: "|1h| ≥ 1% AND last 5m inside the prior 5m",
    vote: "WAIT for the next 5m",
    conf_formula: "sit",
    invalidate_if: "next 5m breaks the inside range",
    start: "SHADOW",
  },
  {
    id: "PULSE.vol_agree",
    owner: "PULSE",
    question: "Does volume spike agree with price?",
    eyes: "1m volume vs median + close",
    fire_when: "vol > 2.2× median AND price same direction",
    vote: "that side",
    conf_formula: "vol multiple",
    invalidate_if: "next bar opposite spike",
    start: "LIVE",
  },
  {
    id: "PULSE.dryup_sit",
    owner: "PULSE",
    question: "Did volume dry up after a push?",
    eyes: "vol vs median",
    fire_when: "vol < 0.45× median after a push",
    vote: "WAIT",
    conf_formula: "dry ratio",
    invalidate_if: "volume returns",
    start: "SHADOW",
  },
  {
    id: "PULSE.climax_sit",
    owner: "PULSE",
    question: "Spike at an extreme with a wick against the bar?",
    eyes: "1m vol + location + wick",
    fire_when: "vol spike at HIGH with upper wick or LOW with lower wick",
    vote: "WAIT — blow-off",
    conf_formula: "sit",
    invalidate_if: "next bar is a full body through the wick",
    start: "SHADOW",
  },
  {
    id: "PULSE.absorb",
    owner: "PULSE",
    question: "High volume, tiny body (effort vs result)?",
    eyes: "vol ratio + body%",
    fire_when: "vol spike AND body < 28% of range",
    vote: "WAIT",
    conf_formula: "sit",
    invalidate_if: "next bar expands with volume",
    start: "SHADOW",
  },
  {
    id: "PULSE.vol_lag_5m",
    owner: "PULSE",
    question: "5m already paid, 1m quiet, 15m still aligned?",
    eyes: "5m vol vs 1m vol + ret15",
    fire_when: "5m vol ≥ 1.8× and 1m < 0.9× and ret15 agrees",
    vote: "with ret15",
    conf_formula: "ret15 edge",
    invalidate_if: "1m volume returns against ret15",
    start: "SHADOW",
  },
  {
    id: "TAPE.persist_imbalance",
    owner: "TAPE",
    question: "Has Kalshi book imbalance held its sign?",
    eyes: "YES vs NO top depth",
    fire_when: "same sign ≥ 4 snapshots",
    vote: "that side",
    conf_formula: "|imbalance| * persistence",
    invalidate_if: "sign flips and holds 2 snapshots",
    start: "LIVE",
  },
  {
    id: "TAPE.flip_after_persist",
    owner: "TAPE",
    question: "Did a 4-print persist just flip on the last two snapshots?",
    eyes: "imbalance_hist",
    fire_when: "older 4 same sign, last 2 opposite",
    vote: "with the flip",
    conf_formula: "fixed 0.58",
    invalidate_if: "imbalance reclaims the old persist",
    start: "SHADOW",
  },
  {
    id: "TAPE.thin_sit",
    owner: "TAPE",
    question: "Is the Kalshi top thin or the spread wide?",
    eyes: "YES/NO size + spread",
    fire_when: "combined size < 2.5 or spread > 5¢",
    vote: "WAIT",
    conf_formula: "sit",
    invalidate_if: "size reprints and spread compresses",
    start: "SHADOW",
  },
  {
    id: "TAPE.size_wipe",
    owner: "TAPE",
    question: "Did one side of the book get wiped while imbalance persists?",
    eyes: "YES sz vs NO sz",
    fire_when: "light side < 18% of heavy AND persist",
    vote: "with the heavy side",
    conf_formula: "fixed 0.6",
    invalidate_if: "wiped side refills",
    start: "SHADOW",
  },
  {
    id: "VEL.spot_lead",
    owner: "VEL",
    question: "Is spot leading YES mid?",
    eyes: "spot 10m vs YES mid",
    fire_when: "|lead bps| meaningful AND YES has not followed",
    vote: "with spot",
    conf_formula: "lead magnitude",
    invalidate_if: "lag closes or spot reverses",
    start: "LIVE",
  },
  {
    id: "VEL.lag_catch_sit",
    owner: "VEL",
    question: "Has YES already followed the spot lead?",
    eyes: "lead bps vs 60s YES rip",
    fire_when: "lead meaningful AND YES rip ≥ 5¢ same sign",
    vote: "WAIT — lag catching up",
    conf_formula: "sit",
    invalidate_if: "lead expands again while YES stalls",
    start: "SHADOW",
  },
  {
    id: "VEL.lead_fade",
    owner: "VEL",
    question: "Spot lead still printed but the last 1m bar flipped against it?",
    eyes: "lead vs last closed 1m",
    fire_when: "lead meaningful AND last 1m opposite",
    vote: "WAIT",
    conf_formula: "sit",
    invalidate_if: "next 1m reclaims the lead",
    start: "SHADOW",
  },
  {
    id: "WHALE.proxy",
    owner: "WHALE",
    question: "Is 1m notional a large-print proxy?",
    eyes: "1m USD notional vs median",
    fire_when: "vol > 2.5× median",
    vote: "with the bar, label PROXY",
    conf_formula: "vol multiple cap",
    invalidate_if: "opposite large-print cluster",
    start: "LIVE",
  },
  {
    id: "WHALE.cluster",
    owner: "WHALE",
    question: "Two+ large 1m prints in the same direction?",
    eyes: "last 6 1m notionals",
    fire_when: "≥2 bars ≥ 1.8× median, same side",
    vote: "with the cluster",
    conf_formula: "vol multiple",
    invalidate_if: "opposite large print prints",
    start: "SHADOW",
  },
  {
    id: "WHALE.absorb",
    owner: "WHALE",
    question: "Large print that closed against its own range (absorption)?",
    eyes: "1m notional + close position",
    fire_when: "proxy bar closed in the wrong third of the range",
    vote: "fade the print",
    conf_formula: "fixed 0.58",
    invalidate_if: "next bar continues the print",
    start: "SHADOW",
  },
  {
    id: "CARRY.persist_fade",
    owner: "CARRY",
    question: "Extreme funding persisting with rising OI?",
    eyes: "8h funding line + OI",
    fire_when: "|funding| extreme ≥ 3 prints AND OI rising",
    vote: "fade funding side",
    conf_formula: "funding z * OI",
    invalidate_if: "funding normalizes while OI still rising",
    start: "LIVE",
  },
  {
    id: "CARRY.unwind",
    owner: "CARRY",
    question: "Extreme funding still printed but OI is falling (unwind)?",
    eyes: "funding persist + OI Δ10m",
    fire_when: "extreme persist AND OI falling",
    vote: "with the unwind (fade crowded side)",
    conf_formula: "funding z",
    invalidate_if: "OI turns back up while funding stays extreme",
    start: "SHADOW",
  },
  {
    id: "CARRY.normalize_sit",
    owner: "CARRY",
    question: "Did extreme funding just print back toward zero?",
    eyes: "funding hist last vs persist",
    fire_when: "older 3 extreme, last print |f| < 0.012%",
    vote: "WAIT",
    conf_formula: "sit",
    invalidate_if: "funding reprints extreme",
    start: "SHADOW",
  },
  {
    id: "CARRY.trend_carry",
    owner: "CARRY",
    question: "Moderate funding agreeing with ret15 while OI builds?",
    eyes: "funding + ret15 + OI",
    fire_when: "0.008% ≤ |f| < 0.02% AND same sign as ret15 AND OI rising",
    vote: "with ret15 (don't fade yet)",
    conf_formula: "fixed 0.56",
    invalidate_if: "funding goes extreme or OI flips",
    start: "SHADOW",
  },
  {
    id: "CARRY.flip_print",
    owner: "CARRY",
    question: "Did the last funding print flip against a 3-print persist?",
    eyes: "funding hist",
    fire_when: "older persist, last print opposite",
    vote: "WAIT",
    conf_formula: "sit",
    invalidate_if: "new persist prints 3 same-sign",
    start: "SHADOW",
  },
  {
    id: "CHAIN.oi_with_price",
    owner: "CHAIN",
    question: "Is OI building with price?",
    eyes: "OI line + price, 2h",
    fire_when: "OI building with price",
    vote: "continuation",
    conf_formula: "oi delta aligned",
    invalidate_if: "OI delta sign flips",
    start: "LIVE",
  },
  {
    id: "CHAIN.oi_against",
    owner: "CHAIN",
    question: "Is OI building against price (divergence)?",
    eyes: "OI BTC + USD Δ10m vs ret15",
    fire_when: "OI delta sign opposite ret15, both nonzero",
    vote: "fade price",
    conf_formula: "fixed 0.58",
    invalidate_if: "OI delta sign flips to agree",
    start: "SHADOW",
  },
  {
    id: "CHAIN.oi_accel",
    owner: "CHAIN",
    question: "Is the last 3m carrying most of the 10m OI move, with price?",
    eyes: "OI Δ3m vs Δ10m + ret15",
    fire_when: "with price AND |Δ3m| ≥ 42% of |Δ10m| same sign",
    vote: "continuation",
    conf_formula: "fixed 0.6",
    invalidate_if: "Δ3m flips against Δ10m",
    start: "SHADOW",
  },
  {
    id: "CHAIN.oi_stall",
    owner: "CHAIN",
    question: "Price moved but OI barely changed?",
    eyes: "|OI Δ10m| / OI vs |ret15|",
    fire_when: "|Δ10m|/OI < 0.2% AND |ret15| ≥ 0.25%",
    vote: "WAIT",
    conf_formula: "sit",
    invalidate_if: "OI starts tracking price",
    start: "SHADOW",
  },
  {
    id: "CHAIN.oi_flush_sit",
    owner: "CHAIN",
    question: "OI dumping in both BTC and USD while 5m is quiet (de-risk, not a cascade)?",
    eyes: "OI BTC + USD Δ10m + ret5",
    fire_when: "BTC and USD Δ10m < 0 AND |ret5| < 0.15%",
    vote: "WAIT",
    conf_formula: "sit",
    invalidate_if: "ret5 expands with the flush",
    start: "SHADOW",
  },
  {
    id: "CASCADE.proxy_flush",
    owner: "CASCADE",
    question: "Real liquidation prints in the last 10 minutes with a 5m push?",
    eyes: "Bybit/OKX/Bitfinex liquidations last 10m",
    fire_when: "≥1 real liq totaling >$10k AND a 5m move",
    vote: "with the squeeze, cap 58",
    conf_formula: "liq size cap 58",
    invalidate_if: "liq feed down or prints stop",
    start: "LIVE",
  },
  {
    id: "CASCADE.early_flush_sit",
    owner: "CASCADE",
    question: "OI flushing before volume spikes?",
    eyes: "OI Δ + vol ratio",
    fire_when: "OI Δ10m < 0 AND vol < 1.4× AND |ret5| > 0.1%",
    vote: "WAIT — early",
    conf_formula: "sit",
    invalidate_if: "volume spikes into the flush",
    start: "SHADOW",
  },
  {
    id: "CASCADE.vol_no_oi",
    owner: "CASCADE",
    question: "Vol spike + return but OI not flushing (not forced)?",
    eyes: "vol + ret5 + OI",
    fire_when: "vol spike AND |ret5| > 0.2% AND OI Δ ≥ 0",
    vote: "with the 5m, lower size",
    conf_formula: "fixed 0.52, cap 58",
    invalidate_if: "OI starts flushing",
    start: "SHADOW",
  },
  {
    id: "CASCADE.exhaust",
    owner: "CASCADE",
    question: "Forced-flow printed then last 1m wicked against?",
    eyes: "real liq + 1m wick",
    fire_when: "real liquidations AND last 1m wick against the 5m",
    vote: "WAIT",
    conf_formula: "sit",
    invalidate_if: "next 1m continues the squeeze",
    start: "SHADOW",
  },
  {
    id: "CASCADE.force_cluster",
    owner: "CASCADE",
    question: "Three+ real liquidation prints with a 5m push?",
    eyes: "liq count last 10m + ret5",
    fire_when: "real liq_n ≥ 3 AND |ret5| > 0.15%",
    vote: "with the 5m, cap 58",
    conf_formula: "fixed 0.55, cap 58",
    invalidate_if: "liq prints stop",
    start: "SHADOW",
  },
  {
    id: "VOLT.dead_sit",
    owner: "VOLT",
    question: "Is realized vol dead?",
    eyes: "ATR% vs median + vol percentile",
    fire_when: "ATR% < 0.12 OR vol percentile < 25",
    vote: "WAIT and raise council bar",
    conf_formula: "deadness",
    invalidate_if: "vol expands through median",
    start: "LIVE",
  },
  {
    id: "VOLT.expand_break",
    owner: "VOLT",
    question: "Did realized vol expand with a directional 15m?",
    eyes: "ATR% + ret15",
    fire_when: "ATR% ≥ 0.22 AND |ret15| ≥ 0.25%",
    vote: "with ret15",
    conf_formula: "ret15 edge",
    invalidate_if: "ATR% dies back under the quiet floor",
    start: "SHADOW",
  },
  {
    id: "VOLT.atr_spike",
    owner: "VOLT",
    question: "Last 1m range ≥ 2.2× median range?",
    eyes: "1m range vs median",
    fire_when: "last range ≥ 2.2× median AND ret5 directional",
    vote: "with the 5m",
    conf_formula: "fixed 0.56",
    invalidate_if: "next bar is a doji inside the spike range",
    start: "SHADOW",
  },
  {
    id: "VOLT.coil_sit",
    owner: "VOLT",
    question: "Are the last 6 1m ranges compressing vs the prior 12?",
    eyes: "1m range median recent vs prior",
    fire_when: "recent median < 65% of prior",
    vote: "WAIT — coil",
    conf_formula: "sit",
    invalidate_if: "a range spike breaks the coil",
    start: "SHADOW",
  },
  {
    id: "VOLT.vol_hot",
    owner: "VOLT",
    question: "Vol percentile ≥ 80 with a 5m push?",
    eyes: "vol pct + ret5",
    fire_when: "vol pct ≥ 80 AND |ret5| ≥ 0.15%",
    vote: "with the 5m",
    conf_formula: "fixed 0.58",
    invalidate_if: "vol pct drops back under 50",
    start: "SHADOW",
  },
  {
    id: "ODDS.cheap_yes",
    owner: "ODDS",
    question: "Is YES cheap to *buy* (ask, not mid) and not still crashing?",
    eyes: "YES ask vs 42¢ + path",
    fire_when: "YES ask ≤ 42¢ AND path not crashing AND not trend-day",
    vote: "UP",
    conf_formula: "distance under 42",
    invalidate_if: "YES mid crosses back through 50",
    start: "LIVE",
  },
  {
    id: "STRIKE.itm_time",
    owner: "STRIKE",
    question: "Is distance to strike large vs time left?",
    eyes: "spot vs strike + mins_left",
    fire_when: "|dist| large vs mins_left",
    vote: "ITM side",
    conf_formula: "dist / (atr * sqrt time)",
    invalidate_if: "spot prints back through strike",
    start: "LIVE",
  },
  {
    id: "STRIKE.magnet_sit",
    owner: "STRIKE",
    question: "Are we glued to strike into the last 2.2m?",
    eyes: "|dist| vs 0.5 ATR + clock",
    fire_when: "|dist| < 0.5 ATR AND mins_left < 2.2",
    vote: "WAIT",
    conf_formula: "magnet tightness",
    invalidate_if: "spot leaves the magnet",
    start: "SHADOW",
  },
  {
    id: "CHEAP.value",
    owner: "CHEAP",
    question: "Is a side ≤ 42¢ *to buy* (the ask) on a non-trend day?",
    eyes: "YES ask / NO ask vs 42¢",
    fire_when: "ask ≤ 42¢ AND not trend-day AND spread not a hole",
    vote: "that side — retired to shadow (0 for 8; a cheap side is a runaway window STRIKE already owns)",
    conf_formula: "cheapness",
    invalidate_if: "ORBIT tags trend-day or the ask leaves 42¢",
    start: "SHADOW",
  },
  {
    id: "FADE.60s_rip",
    owner: "FADE",
    question: "Did YES rip 8–12¢ in 60s on a real print, not a vanished quote?",
    eyes: "YES mid 30/60s + last trade age + spread",
    fire_when: "rip ≥ 8–12¢ AND a trade in 20s AND spread ≤ 6¢ AND not trend-day",
    vote: "fade the rip",
    conf_formula: "rip size",
    invalidate_if: "mid makes a new extreme in the rip direction",
    start: "LIVE",
  },
  {
    id: "ORBIT.quiet_raise_bar",
    owner: "ORBIT",
    question: "Is this a quiet regime?",
    eyes: "session / ATR% / vol% / 1h ret",
    fire_when: "quiet regime",
    vote: "do not vote a side; raise confluence bar",
    conf_formula: "quietness",
    invalidate_if: "ATR percentile crosses expansion line",
    start: "LIVE",
  },
  {
    id: "ORBIT.weekend_thin",
    owner: "ORBIT",
    question: "Is this a UTC weekend book?",
    eyes: "UTC weekday",
    fire_when: "Saturday or Sunday UTC",
    vote: "do not vote a side; raise bar (thinner book)",
    conf_formula: "sit",
    invalidate_if: "weekday session",
    start: "LIVE",
  },
  {
    id: "ORBIT.trend_day",
    owner: "ORBIT",
    question: "Is this a trend-day (1h run + volume)?",
    eyes: "|ret1h| + vol%",
    fire_when: "|ret1h| ≥ 1.2% AND vol% ≥ 60",
    vote: "do not vote a side; license fade-sits",
    conf_formula: "sit",
    invalidate_if: "1h ret or volume dies",
    start: "LIVE",
  },
  {
    id: "CLOCK.session_prior",
    owner: "CLOCK",
    question: "Does this hour/weekday have a Wilson prior?",
    eyes: "UTC session + weekday pocket",
    fire_when: "that hour/weekday n ≥ 8 and Wilson ≥ 55%",
    vote: "soft prior only — cannot flip the chair alone",
    conf_formula: "Wilson prior cap 58",
    invalidate_if: "CLOCK does not flip alone",
    start: "LIVE",
  },
  {
    id: "CLOCK.final_sit",
    owner: "CLOCK",
    question: "Are we inside the last 4 minutes?",
    eyes: "mins left / phase FINAL",
    fire_when: "phase FINAL or < 4m left",
    vote: "WAIT — STRIKE owns the clock",
    conf_formula: "sit",
    invalidate_if: "back into MID with > 4m left",
    start: "LIVE",
  },
  {
    id: "INDEX.settle_fair",
    owner: "INDEX",
    question: "Does the settlement-rule fair value beat one side's ask by more than the fee?",
    eyes: "lab fair (BRTI index vs strike, settlement average) vs the asks",
    fire_when: "lab live AND fair − ask − fee ≥ index.edge (3¢), no chalk, no quote hole",
    vote: "the side the fair favours",
    conf_formula: "0.4 + 0.6 × |fair − 50| / 50",
    invalidate_if: "the fair crosses back through the ask",
    start: "SHADOW",
  },
  {
    id: "INDEX.locked_avg",
    owner: "INDEX",
    question: "With part of the settlement average already locked, is one ask still stale?",
    eyes: "locked final-minute prints + lab fair vs the asks",
    fire_when: "lab live AND locked prints ≥ index.locked (10) AND fair − ask − fee ≥ index.edge",
    vote: "the side the locked average favours",
    conf_formula: "0.4 + 0.6 × |fair − 50| / 50",
    invalidate_if: "the running average crosses the strike",
    start: "SHADOW",
  },
  {
    id: "WIRE.extreme_fng",
    owner: "WIRE",
    question: "Is Fear & Greed a hot extreme (daily path agrees)?",
    eyes: "F&G number + 7-day spark (daily, not 15m)",
    fire_when: "≤ 20 with 7d still falling, or ≥ 80 with 7d still rising",
    vote: "tag only — WIRE does not vote a side",
    conf_formula: "distance past band",
    invalidate_if: "index leaves the extreme band or 7d path cools",
    start: "LIVE",
  },
  {
    id: "WARDEN.both_down",
    owner: "WARDEN",
    question: "Are both spot and Kalshi down?",
    eyes: "feed health table",
    fire_when: "spot AND Kalshi down",
    vote: "Chair veto WAIT 92 (never a side)",
    conf_formula: "fixed 92",
    invalidate_if: "both feeds print fresh",
    start: "LIVE",
  },
  {
    id: "WARDEN.seq_gap",
    owner: "WARDEN",
    question: "Did Kalshi sequence continuity break?",
    eyes: "seq / gap / last-ok",
    fire_when: "gap, held, or reconnect",
    vote: "silence book+tape seats (never a side)",
    conf_formula: "fixed 84",
    invalidate_if: "sequence continuous again",
    start: "LIVE",
  },
  {
    id: "WARDEN.derivs_down",
    owner: "WARDEN",
    question: "Is the derivs feed down?",
    eyes: "funding / OI health",
    fire_when: "derivs DOWN",
    vote: "silence CARRY/CHAIN/CASCADE (never a side)",
    conf_formula: "fixed 78",
    invalidate_if: "derivs print live",
    start: "LIVE",
  },
  {
    id: "WARDEN.semantic",
    owner: "WARDEN",
    question: "Do the prints make sense?",
    eyes: "strike, crossed book, missing 1m bars, frozen OI",
    fire_when: "zero strike, crossed YES/NO, gap in 1m candles, or OI frozen ≥ 8m",
    vote: "silence the family that is garbage (never a side)",
    conf_formula: "fixed 82",
    invalidate_if: "prints make sense again",
    start: "LIVE",
  },
];

function blankCard(seed: SkillSeed): SkillCard {
  return {
    id: seed.id,
    owner: seed.owner,
    question: seed.question,
    eyes: seed.eyes,
    fire_when: seed.fire_when,
    vote: seed.vote,
    conf_formula: seed.conf_formula,
    invalidate_if: seed.invalidate_if,
    status: seed.start,
    n: 0,
    hits: 0,
    wait_good: 0,
    wait_miss: 0,
    wilson: 0,
    brier_sum: 0,
    brier_n: 0,
    brier: 0,
    ev_sum: 0,
    ev_n: 0,
    ev: 0,
    streak_wrong: 0,
    last20: [],
    pocket: {},
    rule: SKILL_RULES[seed.id],
  };
}

export function freshLearner(): Learner {
  const skills: Record<string, SkillCard> = {};
  for (const s of SKILL_SEEDS) skills[s.id] = blankCard(s);
  const seat_n = {} as Record<string, number>;
  const seat_hits = {} as Record<string, number>;
  const seat_calls = {} as Record<string, number>;
  const fade_strength = {} as Record<string, number>;
  const seat_recent = {} as Record<string, number[]>;
  const seat_w = {} as Record<string, number>;
  const knobs = {} as Record<string, SeatKnobs>;
  for (const id of SEAT_IDS) {
    knobs[id] = { edge_mult: 1, speak_offset: 0, prev_offset: null, benched_until: 0, updated_at: 0, reason: "" };
    seat_n[id] = 0;
    seat_hits[id] = 0;
    seat_calls[id] = 0;
    fade_strength[id] = 0;
    seat_recent[id] = [];
    seat_w[id] = SEAT_BY_ID[id].base;
  }
  return {
    skills,
    knobs,
    seat_n,
    seat_hits,
    seat_calls,
    seat_calib_debt: {},
    seat_review_at: {},
    seat_recent,
    seat_w,
    seat_scalp: {},
    fade_strength,
    conf_bins: {
      "50-60": { n: 0, hits: 0 },
      "60-70": { n: 0, hits: 0 },
      "70-80": { n: 0, hits: 0 },
      "80-92": { n: 0, hits: 0 },
    },
    graded_windows: 0,
    learn_phase: "EXPLORE",
    settle_tape: [],
    huddle_log: [],
    window_memory: {
      prior_settles: [],
      path_since_entry: [],
      streak_n: 0,
      streak_side: null,
      entry_spot: 0,
      entry_lean: null,
      tapes: [],
    },
    law_wrongs: 0,
    lockdown_until: 0,
    lockdown: false,
    lockdown_windows_left: 0,
    candidate: null,
    last_huddle: 0,
    last_huddle_n: 0,
    chair_recent: [],
    chair_ev_sum: 0,
    chair_ev_n: 0,
    chair_wait_n: 0,
    chair_wait_good: 0,
    wf_chair: [],
    thresholds: freshThresholds(),
    last_feats: {},
    last_regime: "",
    pattern_book: {},
    window_patterns: [],
  };
}

export function liveSkills(learner: Learner, seat: SeatId): SkillCard[] {
  return Object.values(learner.skills).filter(
    (s) => s.owner === seat && s.status === "LIVE",
  );
}

export function shadowSkills(learner: Learner, seat: SeatId): SkillCard[] {
  return Object.values(learner.skills).filter(
    (s) => s.owner === seat && s.status === "SHADOW",
  );
}

export function skillCounts(learner: Learner, seat: SeatId) {
  const cards = Object.values(learner.skills).filter((s) => s.owner === seat);
  return {
    live: cards.filter((s) => s.status === "LIVE").length,
    shadow: cards.filter((s) => s.status === "SHADOW").length,
    bench: cards.filter((s) => s.status === "BENCH").length,
    candidate: cards.filter((s) => s.status === "CANDIDATE").length,
  };
}

export function refreshDerived(card: SkillCard): SkillCard {
  card.wilson = card.n > 0 ? wilsonLower(card.hits, card.n) : 0;
  card.brier = card.brier_n > 0 ? card.brier_sum / card.brier_n : 0;
  card.ev = card.ev_n > 0 ? card.ev_sum / card.ev_n : 0;
  return card;
}

export function parentSeatWilson(learner: Learner, seat: SeatId): number {
  const n = learner.seat_n[seat] ?? 0;
  const h = learner.seat_hits[seat] ?? 0;
  return n > 0 ? wilsonLower(h, n) : 0;
}

export function recencyRate(card: SkillCard): number {
  if (card.last20.length >= 4) {
    return card.last20.reduce((a, b) => a + b, 0) / card.last20.length;
  }
  if (card.n > 0) return card.hits / card.n;
  return 0.5;
}

export function skillScore(card: SkillCard): number {
  const rec = recencyRate(card);
  if (card.n < 8) return 0.48 + rec * 0.08;
  const ev = card.ev_n > 0 ? card.ev : 0;
  const evTerm = clamp((ev + 4) / 16, 0, 1);
  return rec * 0.45 + card.wilson * 0.3 + evTerm * 0.25;
}

export function phaseOfWindows(n: number): LearnPhase {
  if (n < 15) return "EXPLORE";
  if (n < 80) return "CALIBRATE";
  return "EXPLOIT";
}

export function huddleEvery(phase: LearnPhase): number {
  if (phase === "EXPLORE") return 5;
  if (phase === "CALIBRATE") return 10;
  return 15;
}

export function promoThreshold(phase: LearnPhase): { n: number; wilson: number } {
  if (phase === "EXPLORE") return { n: 12, wilson: 0.52 };
  if (phase === "CALIBRATE") return { n: 18, wilson: 0.54 };
  return { n: 24, wilson: 0.55 };
}

export function benchThreshold(phase: LearnPhase): number {
  if (phase === "EXPLORE") return 0.34;
  if (phase === "CALIBRATE") return 0.42;
  return 0.48;
}
