import { useState } from "react";
import type { ChairResult, CallLogRow, Snapshot } from "@/lib/desk/types";
import type { BooksWindow } from "@/lib/desk/books";
import { bookState } from "@/lib/desk/book-floor";
import { plainLine } from "@/lib/desk/chair-words";
import { whatHappened, whatWouldChange, MULTI_BLOCKER_LINE } from "@/lib/desk/guided-continuity";
import { useCountdownText } from "@/lib/desk/hooks";
import { beacon } from "@/lib/desk/beacon";
import { cn } from "@/lib/utils";
import { Tip } from "./Tip";
